url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Columbus Ruby Brigade

# These are used for SEO plugin
logo: "/assets/images/logo.png"
twitter:
  username: columbusrb
social:
  links:
    - https://x.com/columbusrb
    - https://bsky.app/profile/columbusrb.bsky.social
    - https://www.linkedin.com/company/columbus-ruby-brigade
    - https://github.com/columbusrb
    - https://www.meetup.com/columbusrb/
webmaster_verifications:
  google: "tC9CVUBOtomO3fA3fgNqmb6OSq-FQuzJTErmIM8oyWM"

future: true

pagination:
  enabled: true
  sort_reverse: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-tailwindcss
  - jekyll-seo-tag
