url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Columbus Ruby Brigade

future: true

pagination:
  enabled: true
  sort_reverse: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
